services:
  # ----------------------------------------
  # INFRASTRUCTURE SERVICES
  # ----------------------------------------
  
  
  
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: metriflow-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: mypassword
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    networks:
      - metriflow-net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 20s

  redis:
    image: redis:7-alpine
    container_name: metriflow-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - metriflow-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  # ----------------------------------------
  # APPLICATION SERVICES
  # ----------------------------------------
  #
  #  metriflow-api:
  #    container_name: metriflow-api
  #    build:
  #      context: .
  #      dockerfile: src/Execution/Metriflow.API/Dockerfile
  #    restart: always
  #    depends_on:
  #      - db
  #      - redis
  #    environment:
  #      ConnectionStrings__Sqlserver: Server=db,1433;Database=metriflow_db;User Id=sa;Password=${DB_PASSWORD:-localpassword123!};TrustServerCertificate=True;
  #      ConnectionStrings__Redis: redis:6379
  #    ports:
  #      - "8080:8080"
  #    networks:
  #      - metriflow-net
  #
  #  metriflow-correlation-worker:
  #    container_name: metriflow-correlation-worker
  #    build:
  #      context: .
  #      dockerfile: src/Execution/Metriflow.Correlation.Worker/Dockerfile
  #    restart: always
  #    depends_on:
  #      rabbitmq:
  #        condition: service_healthy
  #      redis:
  #        condition: service_healthy
  #    environment:
  #      - RabbitMQ__HostName=rabbitmq
  #      - RabbitMQ__Port=5672
  #      - RabbitMQ__UserName=user
  #      - RabbitMQ__Password=mypassword
  #      - ConnectionStrings__Redis=redis:6379
  #    networks:
  #      - metriflow-net
  #
  metriflow-aggregation-worker:
    container_name: metriflow-AggregationWorker
    build:
      context: .
      dockerfile: src/Execution/Metriflow.AggregationWorker/Dockerfile
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_healthy
    environment:
      ConnectionStrings__Postgres: Host=database;Port=5432;Database=metriflowdb;Username=postgres;Password=0000
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: user
      RabbitMQ__Password: mypassword
      RabbitMQ__Exchange: analytics.raw
      RabbitMQ__Queues__IntervalAggregation: metriflow.interval.aggregation
      RabbitMQ__Queues__DailyAggregation: metriflow.daily.aggregation
      RabbitMQ__Queues__MonthlyAggregation: metriflow.monthly.aggregation
      RabbitMQ__Queues__YearlyAggregation: metriflow.yearly.aggregation
      RabbitMQ__Queues__AggregationCompleted: metriflow.aggregation.completed
      RabbitMQ__Queues__AggregationFailed: metriflow.aggregation.failed
      RabbitMQ__Queues__GA: metriflow.analytics.GA
      RabbitMQ__Queues__PSI: metriflow.analytics.PSI    
    networks:
      - metriflow-net

  metriflow-producers:
    container_name: metriflow-producers
    build:
      context: .
      dockerfile: src/Execution/Metriflow.Producer/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      metriflow-aggregation-worker:
          condition: service_started
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=user
      - RabbitMQ__Password=mypassword
      - RabbitMQ__Exchange=analytics.raw
      - RabbitMQ__Queues__GA=metriflow.analytics.GA
      - RabbitMQ__Queues__PSI=metriflow.analytics.PSI
    networks:
      - metriflow-net 


  database:
    image: postgres:17
    container_name: Metriflow_postgreSQL_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: metriflowdb
    ports:
      - "6800:5432"
    volumes:
      - metriflow_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d metriflowdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - metriflow-net
# ----------------------------------------
# VOLUMES & NETWORKS
# ----------------------------------------
volumes:
  metriflow_postgres_data:

networks:
  metriflow-net:
    driver: bridge
