// <auto-generated />
using System;
using Metriflow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Metriflow.Infrastructure.Migrations
{
    [DbContext(typeof(MetriflowDbContext))]
    [Migration("20260518065203_Create_StageGARecords_Procedure")]
    partial class Create_StageGARecords_Procedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Metriflow.Domain.Entities.AggregateRecomputeQueue", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("IntervalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CeratedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("PageId", "Date", "IntervalId");

                    b.ToTable("AggregateRecomputeQueue");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.AggregationProgress", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Correlation")
                        .HasColumnType("bit");

                    b.Property<bool>("Daily")
                        .HasColumnType("bit");

                    b.Property<bool>("Interval")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Monthly")
                        .HasColumnType("bit");

                    b.Property<bool>("Quarterly")
                        .HasColumnType("bit");

                    b.Property<bool>("Weekly")
                        .HasColumnType("bit");

                    b.Property<bool>("Yearly")
                        .HasColumnType("bit");

                    b.HasKey("PageId", "Date")
                        .HasName("PK_AggregationProgress");

                    b.HasIndex("Correlation");

                    b.HasIndex("Daily");

                    b.HasIndex("Interval");

                    b.HasIndex("Monthly");

                    b.HasIndex("Quarterly");

                    b.HasIndex("Yearly");

                    b.ToTable("AggregationProgresses");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.DailyAnalytics", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double>("AvgPerformance")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalSessions")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalUsers")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.HasKey("PageId", "Date");

                    b.ToTable("DailyAnalytics");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.MonthlyAnalytic", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("YearMonth")
                        .HasColumnType("date");

                    b.Property<double>("AvgPerformance")
                        .HasColumnType("float");

                    b.Property<long>("TotalSessions")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalUsers")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.HasKey("PageId", "YearMonth");

                    b.ToTable("MonthlyAnalytics");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Path = "home"
                        },
                        new
                        {
                            Id = 2,
                            Path = "about"
                        },
                        new
                        {
                            Id = 3,
                            Path = "contact"
                        },
                        new
                        {
                            Id = 4,
                            Path = "books"
                        },
                        new
                        {
                            Id = 5,
                            Path = "authors"
                        },
                        new
                        {
                            Id = 6,
                            Path = "bestsellers"
                        },
                        new
                        {
                            Id = 7,
                            Path = "highest_rate"
                        },
                        new
                        {
                            Id = 8,
                            Path = "shop"
                        },
                        new
                        {
                            Id = 9,
                            Path = "book"
                        },
                        new
                        {
                            Id = 10,
                            Path = "historical_books"
                        },
                        new
                        {
                            Id = 11,
                            Path = "fiction_books"
                        },
                        new
                        {
                            Id = 12,
                            Path = "non_fiction_books"
                        },
                        new
                        {
                            Id = 13,
                            Path = "dotnet_books"
                        },
                        new
                        {
                            Id = 14,
                            Path = "javascript_books"
                        },
                        new
                        {
                            Id = 15,
                            Path = "operating_system_books"
                        },
                        new
                        {
                            Id = 16,
                            Path = "memory_management_books"
                        },
                        new
                        {
                            Id = 17,
                            Path = "java_books"
                        },
                        new
                        {
                            Id = 18,
                            Path = "software_engineering_books"
                        },
                        new
                        {
                            Id = 19,
                            Path = "dotnet_5"
                        },
                        new
                        {
                            Id = 20,
                            Path = "dotnet_6"
                        },
                        new
                        {
                            Id = 21,
                            Path = "dotnet_7"
                        },
                        new
                        {
                            Id = 22,
                            Path = "dotnet_8"
                        },
                        new
                        {
                            Id = 23,
                            Path = "dotnet_9"
                        },
                        new
                        {
                            Id = 24,
                            Path = "dotnet_10"
                        });
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.PageAnalytics", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<long>("LcpMs")
                        .HasColumnType("bigint");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<double>("PerformanceScore")
                        .HasColumnType("float");

                    b.Property<long>("Sessions")
                        .HasColumnType("bigint");

                    b.Property<long>("Users")
                        .HasColumnType("bigint");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.HasIndex("Interval");

                    b.HasIndex("PageId", "DateOnly", "Interval")
                        .HasDatabaseName("IX_PageAnalytics_ReAggregation");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("PageId", "DateOnly", "Interval"), false);

                    b.ToTable("PageAnalytics");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.TableRowsCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RowsCount")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TableRowsCounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RowsCount = 0,
                            TableName = "GARecords"
                        },
                        new
                        {
                            Id = 2,
                            RowsCount = 0,
                            TableName = "PSARecords"
                        },
                        new
                        {
                            Id = 3,
                            RowsCount = 0,
                            TableName = "AggregationProgresses"
                        },
                        new
                        {
                            Id = 4,
                            RowsCount = 0,
                            TableName = "PageAnalytics"
                        },
                        new
                        {
                            Id = 5,
                            RowsCount = 0,
                            TableName = "TimeIntervalsAnalytics"
                        },
                        new
                        {
                            Id = 6,
                            RowsCount = 0,
                            TableName = "DailyAnalytics"
                        },
                        new
                        {
                            Id = 7,
                            RowsCount = 0,
                            TableName = "MonthlyAnalytics"
                        },
                        new
                        {
                            Id = 8,
                            RowsCount = 0,
                            TableName = "YearlyAnalytics"
                        });
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.TimeInterval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Interval")
                        .HasColumnType("tinyint");

                    b.Property<string>("IntervalDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Interval")
                        .IsUnique();

                    b.ToTable("TimeIntervals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Interval = (byte)1,
                            IntervalDescription = "12-hour: 12:00 AM – 3:59 AM | 24-hour: 00:00 – 03:59"
                        },
                        new
                        {
                            Id = 2,
                            Interval = (byte)2,
                            IntervalDescription = "12-hour: 4:00 AM – 7:59 AM | 24-hour: 04:00 – 07:59"
                        },
                        new
                        {
                            Id = 3,
                            Interval = (byte)3,
                            IntervalDescription = "12-hour: 8:00 AM – 11:59 AM | 24-hour: 08:00 – 11:59"
                        },
                        new
                        {
                            Id = 4,
                            Interval = (byte)4,
                            IntervalDescription = "12-hour: 12:00 PM – 3:59 PM | 24-hour: 12:00 – 15:59"
                        },
                        new
                        {
                            Id = 5,
                            Interval = (byte)5,
                            IntervalDescription = "12-hour: 4:00 PM – 7:59 PM | 24-hour: 16:00 – 19:59"
                        },
                        new
                        {
                            Id = 6,
                            Interval = (byte)6,
                            IntervalDescription = "12-hour: 8:00 PM – 11:59 PM | 24-hour: 20:00 – 23:59"
                        });
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.TimeIntervalAnalytic", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("TimeIntervalId")
                        .HasColumnType("int");

                    b.Property<double>("AvgPerformance")
                        .HasColumnType("float");

                    b.Property<long>("TotalSessions")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalUsers")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.HasKey("PageId", "Date", "TimeIntervalId");

                    b.HasIndex("TimeIntervalId");

                    b.ToTable("TimeIntervalsAnalytics");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.Workers.GARecord", b =>
                {
                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrelation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<long>("Sessions")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Ticks")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date")
                        .HasAnnotation("Relational:JsonPropertyName", "Date");

                    b.Property<long>("Users")
                        .HasColumnType("bigint");

                    b.Property<long>("Views")
                        .HasColumnType("bigint");

                    b.HasIndex("IsCorrelation")
                        .HasFilter("[IsCorrelation] = 1");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("IsCorrelation"), false);

                    b.HasIndex("PageId", "Ticks");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("PageId", "Ticks"), false);

                    b.ToTable("GARecords");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.Workers.PSARecord", b =>
                {
                    b.Property<DateOnly>("DateOnly")
                        .HasColumnType("date");

                    b.Property<Guid>("Hash")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrelation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("LCP_MS")
                        .HasColumnType("bigint");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ticks")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date")
                        .HasAnnotation("Relational:JsonPropertyName", "Date");

                    b.HasIndex("IsCorrelation")
                        .HasFilter("[IsCorrelation] = 1");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("IsCorrelation"), false);

                    b.HasIndex("PageId", "Ticks");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("PageId", "Ticks"), false);

                    b.ToTable("PSARecords");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.YearlyAnalytics", b =>
                {
                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<double>("AvgPerformance")
                        .HasColumnType("float");

                    b.Property<long>("TotalSessions")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalUsers")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalViews")
                        .HasColumnType("bigint");

                    b.HasKey("PageId", "Year");

                    b.ToTable("YearlyAnalytics");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.AggregationProgress", b =>
                {
                    b.HasOne("Metriflow.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.DailyAnalytics", b =>
                {
                    b.HasOne("Metriflow.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.MonthlyAnalytic", b =>
                {
                    b.HasOne("Metriflow.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.PageAnalytics", b =>
                {
                    b.HasOne("Metriflow.Domain.Entities.TimeInterval", "TimeInterval")
                        .WithMany()
                        .HasForeignKey("Interval")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Metriflow.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("TimeInterval");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.TimeIntervalAnalytic", b =>
                {
                    b.HasOne("Metriflow.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Metriflow.Domain.Entities.TimeInterval", "TimeInterval")
                        .WithMany()
                        .HasForeignKey("TimeIntervalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("TimeInterval");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.YearlyAnalytics", b =>
                {
                    b.HasOne("Metriflow.Domain.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });
#pragma warning restore 612, 618
        }
    }
}
