// <auto-generated />
using System;
using Metriflow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Metriflow.Infrastructure.Migrations
{
    [DbContext(typeof(MetriflowDbContext))]
    partial class MetriflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Metriflow.Domain.Entities.DailyStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AvgPerformance")
                        .HasColumnType("float");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("int");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PageId", "Date")
                        .HasName("AK_DailyStats_PageDay");

                    b.HasIndex("Date");

                    b.ToTable("DailyStat");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.MonthlyStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AvgPerformance")
                        .HasColumnType("float");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("int");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int");

                    b.Property<string>("YearMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("PageId", "YearMonth")
                        .HasName("AK_MonthlyStat_PageMonth");

                    b.HasIndex("YearMonth");

                    b.ToTable("MonthlyStat");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Page");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.YearlyStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AvgPerformance")
                        .HasColumnType("float");

                    b.Property<int>("PageId")
                        .HasColumnType("int");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("int");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("int");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("PageId", "Year")
                        .HasName("AK_YearlyStats_PageYear");

                    b.HasIndex("Year");

                    b.ToTable("YearlyStat");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.DailyStat", b =>
                {
                    b.HasOne("Metriflow.Domain.Entities.Page", "Page")
                        .WithMany("DailyStatsRecords")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.MonthlyStat", b =>
                {
                    b.HasOne("Metriflow.Domain.Entities.Page", "Page")
                        .WithMany("MonthlyStatsRecords")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.YearlyStat", b =>
                {
                    b.HasOne("Metriflow.Domain.Entities.Page", "Page")
                        .WithMany("YearlyStatsRecords")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("Metriflow.Domain.Entities.Page", b =>
                {
                    b.Navigation("DailyStatsRecords");

                    b.Navigation("MonthlyStatsRecords");

                    b.Navigation("YearlyStatsRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
